### ISSUE TITLE
Ultrawide cutscenes displayed in 16:9 ratio

### ISSUE THREAD

**Issue by jordanmerkel** [34736384/genshin-fps-unlock#106]
Hello, reporting a **_minor_** bug. 

The issue:
The pre-made video cutscenes are displayed in 16:9 format rather than the intended ultrawide resolution. To be clear, the cutscenes I am referring to are the ones that are typically shared on their YouTube. This issue is consistent across all of the video cutscenes. (an example of the cutscenes I am referring to: https://www.youtube.com/watch?v=UDQ7m2L9sK8)

What was expected:
The video cutscenes should be displayed in the ultrawide resolution as the base game does currently.

**Comment by Transcan** [comment]
That has nothing to do with the FPS unlocker. The game is made like that.
Those cutscenes are in fact pre-rendered video, not in-game engine. 16:9 is the standard, so its normal they are only in that aspect ratio.
It would be a waste of disk space (and time) to also render the same video for each aspect ratio out there.
We are lucky that the game runs in 21:9, Honkai Impact doesn't...

**Comment by jordanmerkel** [comment]
> That has nothing to do with the FPS unlocker. The game is made like that.

The base game (non-fps unlocker) crops and displays the 21:9 version. The unlocker does not do this.

**Comment by Transcan** [comment]
You mean, the non modded game displays those videos in 21:9 (filling all the screen)?
If so:
- It maintains the aspect ratio without any crop (uncertain because it would mean that there are two versions of the videos, one in 16:9 and one in 21:9. Something that do not exists)
- It stretches the image to fill the screen (not maintaing the aspect ratio). Something that can be done by your monitor trying to scale the image to fill the whole screen. And because the FPS unlocker locks the screen size, that streeching will cease.
- Or it crops the top and bottom of the image (missing those parts). Also could be explained by the monitor settings.

Anyways, if the game behave differently when modded, it must be because in those cutscenes the game switch to a screen resolution of 1920x1080, and your monitor handles that resolution in a different way than when using the mod, which maintain the same resolution of 3440x1440 at all times (if you use that option in the mod).

Just my guessing... Try to disable 'custom resolution' in the mod, if you has it enabled, and check if that helps.

**Comment by jerichosy** [comment]
I use the unlocker and play in fullscreen on an ultrawide display, but cutscenes display in 21:9 for me. Neither do I have custom resolution enabled nor do I start the game in exclusive fullscreen. 

I'd like to add though that cropped 21:9 cutscenes isn't always desirable messes up the framing. Example:
![Genshin_Impact_2023 01 15_-_16 55 12 28 mp4_snapshot_00 55 19 683](https://user-images.githubusercontent.com/69558553/212809760-31ebddd9-9275-4c90-9dae-dc933272dbf5.jpg)
![image](https://user-images.githubusercontent.com/69558553/212809806-456a3b9d-0f96-41b2-9b90-0c7199f7b167.png)

**Comment by Transcan** [comment]
I see, thanks for the example, it was very enlightening.
So it's my third guess, but nothing related with the monitor.
Looking at your examples, you can see your ID in both images, so the monitor isn't cropping, it is displaying what it is receiving.
If those scenes aren't cropped without the unlocker (displaying black bars at left/right), then it's clear that the unlocker messes with the game's routine of switching resolutions when playing a video scene, and so the cropping appears.
If the only related options in the app doesn't help, then I don't think it can be solved. Looks like collateral damage to me.
But only the dev can really answer this question.

**Comment by Transcan** [comment]
Today I tested this issue with the video cutscene that plays when a new Battle Pass begins...
In both cases (with and without fps_unlocker) the video plays in full screen (21:9) but cropped (cutting part of the image at top and bottom).
I didn't know if this behaviour have being like that since always, because I recently bought the monitor and this is the first time I see cutscene in it.
Anyways, the visual is exactly the same with or without the app (video is cropped).
Looks like the game itself renders the videos in a bad way when using a UltraWide resolution, at least in my case.
The fps_unlocker is not the cause for the crop and I guess, it can't solve it either.

**Comment by jerichosy** [comment]
Sidenote, you can replay a pre-rendered cutscene by "reading" the Wind, Courage, and Wings quest item which plays the gliding manual cutscene. 

Anyways, I tried using exclusive fullscreen and the cutscene still plays in its cropped 21:9 form. Without much info from OP on what his settings are, I can't reproduce the issue.

**Comment by system2ckc** [comment]
> Sidenote, you can replay a pre-rendered cutscene by "reading" the Wind, Courage, and Wings quest item which plays the gliding manual cutscene.
> 
> Anyways, I tried using exclusive fullscreen and the cutscene still plays in its cropped 21:9 form. Without much info from OP (@jordanmerkel) on what his settings are, I can't seem to reproduce the issue.

Honestly id rather have the 16:9 version > the cropped 21:9. Didn't know about this before 3.6 update so now I can't test. Temporarily turned off Fps Unlocker for now since I heard 3.6 maybe introduced some new anti-cheat?

**Comment by Transcan** [comment]
No idea about the new anti-cheat, I'm still using the unlocker and I'm fine so far.

About the uncropped version of the cut scenes:
The fps unlocker doesn't change them and is not the cause for the cropping:
If you use a resolution with an aspect ratio of 21:9, they will be cropped. If the resolution es 16:9, they will not.
This is the actual game behaviour, with or without the unlocker.
So the only way to watch the cutscenes uncropped in an ultrawide screen, is playing with a 16:9 aspect ratio screen size (it doesn't matter where you configure the resolution, inside the game itself or inside the unlocker, the result is the same).

In my case, I decided that I prefer to play in ultrawide and re-watch the uncropped version in youtube just in case I missed something (or just to watch them the way they meant to be seen).
Usually MiHoyo uploads them in the official channel. If not, there are plenty youtubers that uploads their walkthroughs and usually is in 16:9.

**Comment by jordanmerkel** [comment]
I had gotten a new pc shortly after I created this issue and had to fresh install everything over. It's working now correctly. Not sure why it was displaying wrong before.

But my settings haven't changed: 151fps, exclusive fullscreen, 3440x1440, auto-disabled vsync, and set to high game process. It wasn't anything special. I also had Nvidia filters on at the time, there's a chance that could be related I'm not sure.

I will close the issue since nobody else has encountered it besides me.

**Comment by Transcan** [comment]
Mmm nVidia filters, thanks for pointing it out.
I'm going to mess with them. I will post my findings if I can replicate the behaviour for the ones that want to see the whole video when playing on 21:9.
