### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Lehner82** [34736384/genshin-fps-unlock#16]
Would it be possible to add a config file with FPS limit and Vsync options that doesn't reset every restart?

**Comment by 34736384** [comment]
It is possible but I don’t see the necessity of it

**Comment by Fractalzdude** [comment]
I don't know how hard it would be to implement but I'd love that option as well, sort of a fire and forget thing since I replaced my shortcut to genshin with this, would be awesome to have a config file, if it's not too troublesome to implement. Thanks for your work by the way, made me enjoy the game a lot more!

**Comment by 34736384** [comment]
added in v1.4
