### ISSUE TITLE
New version 1.4 got quarantined by windows defender

### ISSUE THREAD

**Issue by Ximari77** [34736384/genshin-fps-unlock#20]
Behavior:Win32/DefenseEvasion.A!ml

**Comment by 34736384** [comment]
Whitelist it or compile it yourself, its just a false positive, can't do anything about it

**Comment by Areha11Fz** [comment]
just because this repo is called genshin-fps-unlock, can you remove the reshade and the other things and make this program only for fps unlock because for some of us we don't need reshade? and then makes separated repo for the reshade?, just in case if the reshade things got detected, please and thank you

**Comment by 34736384** [comment]
> just because this repo is called genshin-fps-unlock, can you remove the reshade and the other things and make this program only for fps unlock because for some of us we don't need reshade? and then makes separated repo for the reshade?, just in case if the reshade things got detected, please and thank you

The support for reshade injection is not and will not be a detection vector. Even if reshade is detected as cheat, the problem comes from reshade itself not the injection part
