### ISSUE TITLE
recommendations for default settings

### ISSUE THREAD

**Issue by exciar** [34736384/genshin-fps-unlock#217]
AutoStart = false;
    AutoDisableVSync = true;
    PopupWindow = true;
    Fullscreen = true;
    UseCustomRes = false;
    IsExclusiveFullscreen = false;
    UsePowerSave = false;

**Comment by FooqX** [comment]
here's my recommendations for best performance settings
 
AutoDisableVsync = false (firstly turn it off in game, secondly because it's already turned off in game this option can bug the unlocker for some people)
PopupWindow = false (if true then you will probably have more latency and less reponsiveness etc)
Fullscreen = true (for best responsiveness and least latency)
Window mode = exclusive (for best responsiveness and least latency and less stutters, but if you really switch to something else from the game and you need it quickly, then i dont recommend this because exclusive slows alt+tab switching, but better performance)

**Comment by exciar** [comment]
I have PopupWindow on because I have multiple monitors it prevents just prevents genshin from closing when alt-tab
