### ISSUE TITLE
3DMigoto + FPS Unlocker Collision

### ISSUE THREAD

**Issue by wRca21** [34736384/genshin-fps-unlock#242]
Hello,

I've been introduced to the world of mods a while ago so it's obvious I'd use 3dmigoto, the thing, is when I use it, the FPS unlocker seems to have some sort of issue with working alongside 3dmigoto because instead of the usual 144 fps, I get 60. Every single time. I've tried changing the settings as mentioned in another thread, and also opening genshin with the fps unlocker first and then open 3dmigoto, but it doesn't seem to work for me. Could you please take a look at this?  Thank you!!

PS:I really need the dark loading screen mod, my eyes are killing me 🤣😫

**Comment by HadouGun** [comment]
I find both to work at the same time, start 3dmigoto first then when you start fps unlocker if it counts down on the 3dmigoto box then close both and try again.

**Comment by wRca21** [comment]
For some reason it works now and I did the exact same process I did before 😅 But I'll keep it in mind to start 3dmigoto first from now on, thank you!

**Comment by Nixeld** [comment]
If anyone is still having this problem, you need to add the `d3d11.dll` file from 3DMigoto into the list of DLLs injected using the FPS unlocker.

Go to Genshin FPS Unlocker Options > Settings > DLLs > Add > Select `d3d11.dll` from your 3DMigoto directory.

_Note that Enable HDR must be unchecked under the General tab of the FPS unlocker settings for this to work otherwise you will just see a black screen._
