### ISSUE TITLE
dxvk injection support

### ISSUE THREAD

**Issue by dnblank123** [34736384/genshin-fps-unlock#35]
any future support?

**Comment by 34736384** [comment]
if you are not using reshade then just try just renaming it to ReShade64.dll

**Comment by leonardo-spy** [comment]
@dnblank123 I got a solution, but you will have to be patient...
Firstly, english is not my primary language so sorry for any thing error in my grammar!
I made some changes to inject the dxvk, the dev (@34736384 ) can feel free to adapt it to their project. 

First you need add this dlls (dxvk 64bits) in the same folders that you will add '`unlockfps.exe`', but in '`UNLOCKFPS FOLDER/inject/64/`'
![image](https://i.ibb.co/mv0K37S/img1.png)

Secondly you neesd add this lines later `InjectReshade(pi.hProcess);` and the delay is required because i dont know why this dont work when is instantly:
```
std::this_thread::sleep_for(std::chrono::milliseconds(1150));
Injectdxgi_64(pi.hProcess);    
Injectd3d11_64(pi.hProcess);
```
![image](https://i.ibb.co/MMZhptr/img2.png)

and add this code to load the dlls:
(just copy and edit the function InjectReshade)
![image](https://i.ibb.co/5jyP8cx/img3.png)
 and done! If you wanna see if work it just use processhacker (you can find it in google, but open only later that alrealdy opened genshin, because genshin dont open when processhacker is alrealdy opened) and will see in module one 'd3d11.dll' and two 'dxgi.dll' (i dont know how unload system dxgi, but calm down, dxvk d3d11 only work if dxvk dxgi is working case else will show a resolution error)
![image](https://i.ibb.co/54J0P5m/img4.png)
 I believe that this can be improved :)

**Comment by leonardo-spy** [comment]
@dnblank123 I got a solution, but you will have to be patient...
Firstly, english is not my primary language so sorry for any thing error in my grammar!
I made some changes to inject the dxvk, the dev (@34736384 ) can feel free to adapt it to their project. 

First you need add this dlls (dxvk 64bits) in the same folders that you will add '`unlockfps.exe`', but in '`UNLOCKFPS FOLDER/inject/64/`'
![img1](https://user-images.githubusercontent.com/19514153/148602850-6d2d1aff-596f-4663-969e-4a2cf01c76e9.png)

Secondly you neesd add this lines later `InjectReshade(pi.hProcess);` and the delay is required because i dont know why this dont work when is instantly:
```
std::this_thread::sleep_for(std::chrono::milliseconds(1150));
Injectdxgi_64(pi.hProcess);    
Injectd3d11_64(pi.hProcess);
```
![img2](https://user-images.githubusercontent.com/19514153/148602908-710605a3-f2cb-4405-8794-ef581cddbe05.png)

and add this code to load the dlls:
(just copy and edit the function InjectReshade)
![img3](https://user-images.githubusercontent.com/19514153/148602956-9e2cc703-ded0-45c4-8c00-5d843da8570e.png)
 and done! If you wanna see if work it just use processhacker (you can find it in google, but open only later that alrealdy opened genshin, because genshin dont open when processhacker is alrealdy opened) and will see in module one 'd3d11.dll' and two 'dxgi.dll' (i dont know how unload system dxgi, but calm down, dxvk d3d11 only work if dxvk dxgi is working case else will show a resolution error)
![img4](https://user-images.githubusercontent.com/19514153/148602982-30d7fa7a-6033-4da4-8555-f79475a61922.png)
 I believe that this can be improved :)

**Comment by dnblank123** [comment]
@leonardo-spy Thank you very much. Managed to fix it by adding another sleep thread(?) 
![image](https://user-images.githubusercontent.com/67945097/148631095-c52c3269-d347-4bfc-966a-e539197392fb.png)
![image](https://user-images.githubusercontent.com/67945097/148631103-0e928cd1-3902-41f1-8423-976163bfc3aa.png)

**Comment by leonardo-spy** [comment]
@dnblank123 i find the solution, just wait load this dll '`imagehlp.dll`' and remove delay :)
![img5](https://user-images.githubusercontent.com/19514153/148658638-1a9cf007-cddc-485f-9f2d-7f36b179bf22.png)
code :
```
MODULEENTRY32 himagehlp{};
while (!GetModule(pi.dwProcessId, "imagehlp.dll", &himagehlp))
    std::this_thread::sleep_for(std::chrono::milliseconds(100));

Injectdxgi_64(pi.hProcess);
Injectd3d11_64(pi.hProcess);  
```

**Comment by leonardo-spy** [comment]
update:
in some systems imagehlp dont is started, so replace with `rsaenh.dll` in your code

**Comment by 34736384** [comment]
Check out the latest release https://github.com/34736384/genshin-fps-unlock/releases
Should solve this issue

**Comment by akippnn** [comment]
My bad, dxgi.dll and d3d11.dll goes in the actual game folder, not the root folder. But it won't let me in
![image](https://user-images.githubusercontent.com/80670461/175303469-ed12ee90-4375-40b7-b4e5-29ce54bd03f6.png)
Not surprised, it was worth a shot. Hoping we could run this game in Vulkan somehow on Windows.

**Comment by akippnn** [comment]
My bad, dxgi.dll and d3d11.dll goes in the actual game folder, not the root folder. But it won't let me in
![175303469-ed12ee90-4375-40b7-b4e5-29ce54bd03f6](https://user-images.githubusercontent.com/80670461/175306960-0817bacb-02df-49d3-98a0-3f4ae4b8e231.png)
Not surprised, it was worth a shot. Hoping we could run this game in Vulkan somehow on Windows.

**Comment by dnblank123** [comment]
@akippnn We have similar issue with your first comment, _might_ be a delay or something idk, I'm closing the issue since I don't play the game anyway.

**Comment by ilhan-athn7** [comment]
Hi, if i add dll's right here (in the image), will it work, or  i need to build with above changes?
![image](https://github.com/34736384/genshin-fps-unlock/assets/80551220/265e605b-2809-4810-a21b-168a8d1a41ae)

**Comment by Licykoc** [comment]
> ![untitled](https://user-images.githubusercontent.com/45236574/251197832-2b190685-c652-44d2-8fcf-66babe984f7c.JPG)
> 
> i dont know is this still maintained / related, but now you can run genshin with vulkan without problem
> 
> dxvk gpl-async 2.2-4
> 
> is it bannable? i dont have any idea

are you use win10? how do you use dxvk?

**Comment by merlinch** [comment]
> > ![untitled](https://user-images.githubusercontent.com/45236574/251197832-2b190685-c652-44d2-8fcf-66babe984f7c.JPG)
> > i dont know is this still maintained / related, but now you can run genshin with vulkan without problem
> > dxvk gpl-async 2.2-4
> > is it bannable? i dont have any idea
> 
> are you use win10? how do you use dxvk?

im on windows 11. After the 4.0 update, there's a chance the game doesn't delete the dxgi.dll (i tested with dxvk and specialk local injection) and d3d11.dll crashed. they patched it somehow

**Comment by Licykoc** [comment]
> > > ![untitled](https://user-images.githubusercontent.com/45236574/251197832-2b190685-c652-44d2-8fcf-66babe984f7c.JPG)
> > > i dont know is this still maintained / related, but now you can run genshin with vulkan without problem
> > > dxvk gpl-async 2.2-4
> > > is it bannable? i dont have any idea
> > 
> > 
> > are you use win10? how do you use dxvk?
> 
> im on windows 11. After the 4.0 update, there's a chance the game doesn't delete the dxgi.dll (i tested with dxvk and specialk local injection) and d3d11.dll crashed. they patched it somehow

so dxvk can't work after 4.0 updated? btw, what injector do you use?

**Comment by akippnn** [comment]
DXVK is definitely working even after 4.0, just not when implemented this way.

**Comment by Licykoc** [comment]
> DXVK is definitely working even after 4.0, just not when implemented this way.

all right, so can you use Vulkan to run genshin on windows after 4.0 update?

**Comment by Licykoc** [comment]
> 

I have heard that dxvk can effectively increase fps, so I want to use dxvk.)
Can you help me find an injector with a close anti-cheat? I've searched the Internet and there's nothing available.

**Comment by Licykoc** [comment]
> > > DXVK is definitely working even after 4.0, just not when implemented this way.
> > 
> > 
> > all right, so can you use Vulkan to run genshin on windows after 4.0 update?
> 
> Yes but you need to possibly remove the anti-cheat, so it's not worth it and is beyond the scope of this injector tool.

I have heard that dxvk can effectively increase fps, so I want to use dxvk.)
Can you help me find an injector with a close anti-cheat? I've searched the Internet and there's nothing available.
