### ISSUE TITLE
GSYNC not working

### ISSUE THREAD

**Issue by bean789** [34736384/genshin-fps-unlock#39]
When running genshin without the unlocker, gsync is working correctly: monitor is matching the refresh rate.

Running with the unlocker gsync does not work correctly: monitor's refresh rate changes seemingly randomly, does not match refresh rate of game. 
This causes some inconsistent stutters. I tried an older version 1.2.0 and this problem still occurs for me. Any possible fix? 
Cant play genshin without this tool, thanks for it

**Comment by Johnse53** [comment]
Yeah same with mine too. G-sync does work with the game only and not with fps unlocker by using this command argument on the game shortcut **-screen-fullscreen 1 -window-mode exclusive**.
G-sync doesn't work correctly with the fps unlocker by using command argument **-screen-fullscreen 1 -window-mode exclusive** on the genshin fps unlocker shortcut.

I have an idea though how to make G-sync work by opening genshin fps unlocker and the game itself separately. That way, you can input command argument **-screen-fullscreen 1 -window-mode exclusive** on the game shortcut and running the game from there first. 
And then after that, minimize the game and run fps unlocker to unlock the fps while g-sync is already activated in-game.

I wanted to make request about this. Can you make the fps unlocker to run separately? like we have to run the game first with g-sync on in the game and then run fps unlocker after we minimize the game to unlock its fps later so that g-sync can work correctly in the game. Thanks!

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/releases/tag/v1.4.2
