### ISSUE TITLE
Real Fullscreen

### ISSUE THREAD

**Issue by einfachGaer** [34736384/genshin-fps-unlock#55]
Is it possible to modify the game so that it goes into real fullscreen mode?
Right now its more like a borderless maximized window, if you select fullscreen in settings.

Thanks!

**Comment by DAOWAce** [comment]
Default Unity engine behavior is borderless.

Add **-window-mode exclusive** as a launch argument to get real fullscreen.

**Comment by Spedemix** [comment]
When I run the program with `-add-window-mode exclusive` argument the game actually runs in windowed. However you can enter fullscreen by pressing alt-enter.

The exclusive fullscreen is a bit finicky; if you're using VRR display you may need to alt-enter in and out of fullscreen a couple of times before your screen properly locks to the frame rate (and even then the menu stuff won't be properly frame-paced).

**Comment by DAOWAce** [comment]
> When I run the program with `-add-window-mode exclusive` argument ...

Did you typo in the comment or actually add that to the command line?  Because if you added that to the CL, it's not gonna work.

It's hard to give clarity about something mid-sentence. Only the part in bold is what you copy.

Alternatively, just use [Special K](https://www.pcgamingwiki.com/wiki/Special_K) to force flip model in any borderless game.  Genshin requires the global injector since the anti-cheat removes any extra DLL's in the game folder on launch (or errors on login).

**Comment by FUNNYPOTATO64** [comment]
Is there a way I can run the game with specified resolution in borderless fullscreen mode? I used to be able to do this by creating a shortcut and adding " -popupwindow -screen-height 1440 -screen-width 2560" in the target

**Comment by 34736384** [comment]
Check out the latest release https://github.com/34736384/genshin-fps-unlock/releases
Added GUI and interactive controls for configuring launch options
