### ISSUE TITLE
CRC?

### ISSUE THREAD

**Issue by MuffinLightning** [34736384/genshin-fps-unlock#6]
I'm guessing the fact that you havent been banned means there's no crc on UnityPlayer.dll then? This is similar to what I've been doing, although only for a day now.

I have heard of people getting banned in the past for using fps unlockers, but am unsure what methods they used, do you have any idea?

**Comment by 34736384** [comment]
I do not know if there are more integrity checks after login. The fps limit value is stored on **.data** section of UnityPlayer.dll, **.data** section can be RW'd, therefore they are volatile memory, there shouldn't be any checks on volatile data, because is impractical. Same with vsync value too, it's stored in the heap. 

For those who got banned using a different method, I'm guessing it's either cheat engine is detected or they are modifying **.text** section, which can be hashed and checked

**Comment by MistressAshai** [comment]
> I'm guessing the fact that you havent been banned means there's no crc on UnityPlayer.dll then? This is similar to what I've been doing, although only for a day now.
> 
> I have heard of people getting banned in the past for using fps unlockers, but am unsure what methods they used, do you have any idea?

My main account was banned for a week after using the cheat engine method to unlock frame rate.
But this program has been safe so far.

**Comment by MuffinLightning** [comment]
> I do not know if there are more integrity checks after login. The fps limit value is stored on **.data** section of UnityPlayer.dll, **.data** section can be RW'd, therefore they are volatile memory, there shouldn't be any checks on volatile data, because is impractical. Same with vsync value too, it's stored in the heap.
> 
> For those who got banned using a different method, I'm guessing it's either cheat engine is detected or they are modifying **.text** section, which can be hashed and checked

That's interesting as I would imagine any Cheat Engine method would lead you to the same value, so I'm going to assume it's just a detection on Cheat Engine itself rather than some other check. Thanks

**Comment by Ryrin45** [comment]
The only bans I ever heard of was back when people were using cheat engine to unlock fps. All indications so far is that as long as you avoid cheat engine and just stick to this exe, you'll be fine. Of course there are no guarantees.
